spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    name: test
    url: jdbc:mysql://localhost:3310/SMSDB
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL57Dialect
    show-sql: true
